package dev.codesoapbox.backity.buildtools;

import javax.lang.model.element.Element;
import javax.lang.model.element.TypeElement;

public record GeneratedClassInfo(
        String packageName,
        String className,
        String annotationFqcn,
        String annotationName,
        String parentClassName,
        Element origin
) {

    public static GeneratedClassInfo create(
            TypeElement abstractClassElement,
            TypeElement concreteAnnotation,
            ParentClassInfo parentClassInfo,
            AnnotationConfig annotationConfig
    ) {
        String concreteAnnotationName = concreteAnnotation.getSimpleName().toString();
        String baseName = parentClassInfo.getNameWithoutTestSuffix();
        String concreteName = baseName + concreteAnnotationName + parentClassInfo.testSuffix();

        concreteName = stripClassNameByRegex(concreteName, annotationConfig.stripFromClassNameRegex());

        return new GeneratedClassInfo(
                parentClassInfo.packageName(),
                concreteName,
                concreteAnnotation.getQualifiedName().toString(),
                concreteAnnotationName,
                parentClassInfo.className(),
                abstractClassElement
        );
    }

    private static String stripClassNameByRegex(String concreteName, String regex) {
        concreteName = concreteName.replaceAll(regex, "");
        return concreteName;
    }

    public String getFullClassName() {
        return packageName + "." + className;
    }

    public String getContent() {
        return """
                package %s;
                
                import %s;
                
                /**
                 * Generated by %s.
                 */
                @%s
                public class %s extends %s {
                }
                """.formatted(
                packageName,
                annotationFqcn,
                MultiAnnotationTestProcessor.class.getName(),
                annotationName,
                className,
                parentClassName
        );
    }
}
