backity:
  default-path-template: games/{GAME_PROVIDER_ID}/{TITLE}/{FILENAME}
  in-memory-logs:
    max: '100'
  file-download-queue-scheduler:
    rate-ms: 5000
  gog-auth-scheduler:
    rate-ms: 60000
  gog:
    # https://gogapidocs.readthedocs.io/en/latest/auth.html#get--token
    client-secret: 9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9
    client-id: 46899977096215655
    auth:
      base-url: "http://localhost:1080/gog/auth"
    embed:
      base-url: "http://localhost:1080/gog/embed"
      redirect-uri: "http://localhost:1080/gog/embed/on_login_success"
  h2dump:
    path: dump.sql

spring:
  datasource:
    url: jdbc:h2:file:./backity
    driverClassName: org.h2.Driver
    username: sa
    password: password
  codec:
    max-in-memory-size: 10MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml

openapi:
  project-description: '@project.description@'
  project-title: '@project.name@'
  project-version: '@project.version@'

springdoc:
  default-produces-media-type: application/json
  remove-broken-reference-definitions: 'false'