backity:
  default-path-template: games/{GAME_PROVIDER_ID}/{TITLE}/{FILENAME}
  in-memory-logs:
    max: '100'
  file-download-queue-scheduler:
    rate-ms: 5000
  gog-auth-scheduler:
    rate-ms: 60000
  gog:
    # Secrets deliberately hardcoded
    # https://gogapidocs.readthedocs.io/en/latest/auth.html#get--token
    client-secret: 9d85c43b1482497dbbce61f6e4aa173a433796eeae2ca8c5f6129f2dc4de46d9
    client-id: 46899977096215655
    auth:
      base-url: "https://auth.gog.com"
      redirect-uri: "https://embed.gog.com/on_login_success?origin=client"
    embed:
      base-url: "https://embed.gog.com"
  h2dump:
    path: dump.sql
  filesystem:
    local:
      enabled: true
    s3:
      enabled: false
      buffer-size-in-bytes: 10_000_000
  replication:
    max-retry-attempts: 3
    retry-backoff-in-seconds: 2

spring:
  datasource:
    url: jdbc:h2:file:./backity
    driverClassName: org.h2.Driver
    username: sa
    password: password
  http:
    codecs:
      max-in-memory-size: 10MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-root.xml

  cloud: # S3
    aws:
      s3:
        enabled: ${backity.filesystem.s3.enabled}

openapi:
  project-description: '@project.description@'
  project-title: '@project.name@'
  project-version: '@project.version@'

springdoc:
  default-produces-media-type: application/json
  remove-broken-reference-definitions: 'false'