cors:
    allowed-origins: 'http://localhost:8080,http://localhost:4200'

#logging:
#  level:
#    org:
#      hibernate:
#        type: TRACE
#        SQL: DEBUG
#spring:
#  jpa:
#    properties:
#      hibernate:
#        format_sql: 'true'
#    show-sql: 'true'