/**
 * backend
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {BackupTarget} from './backupTarget';


export interface AddBackupTargetResponse {
    backupTarget?: BackupTarget;
}

