/**
 * backend
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddBackupTargetRequest {
    name: string;
    storageSolutionId: string;
    pathTemplate: string;
}

