/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DiscoveredFileId } from './discoveredFileId';


export interface DiscoveredFile { 
    id?: DiscoveredFileId;
    uniqueId?: string;
    name?: string;
    gameTitle?: string;
    size?: string;
    dateCreated?: string;
    dateModified?: string;
    enqueued?: boolean;
    ignored?: boolean;
}

