/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DownloadStatus = 'DISCOVERED' | 'WAITING' | 'IN_PROGRESS' | 'DOWNLOADED' | 'FAILED';

export const DownloadStatus = {
    Discovered: 'DISCOVERED' as DownloadStatus,
    Waiting: 'WAITING' as DownloadStatus,
    InProgress: 'IN_PROGRESS' as DownloadStatus,
    Downloaded: 'DOWNLOADED' as DownloadStatus,
    Failed: 'FAILED' as DownloadStatus
};

