/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyNaturalId } from './fileCopyNaturalId';


export interface EnqueueFileCopyRequest { 
    fileCopyNaturalId: FileCopyNaturalId;
}

