/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ErrorMessage { 
    /**
     * An optional error id that will uniquely identify the error can be presented to the user
     */
    errorId?: string;
    /**
     * An optional message describing the error (should not be shown to the user)
     */
    message?: string;
    /**
     * An optional message key describing the error. Can be used to show the user relevant information about the error.
     */
    messageKey?: string;
}

