/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const FileCopyStatus = {
    Tracked: 'TRACKED',
    Enqueued: 'ENQUEUED',
    InProgress: 'IN_PROGRESS',
    StoredIntegrityUnknown: 'STORED_INTEGRITY_UNKNOWN',
    StoredIntegrityVerified: 'STORED_INTEGRITY_VERIFIED',
    Failed: 'FAILED'
} as const;
export type FileCopyStatus = typeof FileCopyStatus[keyof typeof FileCopyStatus];

