/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileBackupStatus } from './fileBackupStatus';


export interface FileCopy { 
    status: FileBackupStatus;
    failedReason?: string;
    filePath?: string;
}
export namespace FileCopy {
}


