/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileDiscoveryMessageTopics = '/topic/file-discovery/file-discovered' | '/topic/file-discovery/file-status-changed' | '/topic/file-discovery/progress-update';

export const FileDiscoveryMessageTopics = {
    FileDiscovered: '/topic/file-discovery/file-discovered' as FileDiscoveryMessageTopics,
    FileStatusChanged: '/topic/file-discovery/file-status-changed' as FileDiscoveryMessageTopics,
    ProgressUpdate: '/topic/file-discovery/progress-update' as FileDiscoveryMessageTopics
};

