/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyNaturalIdWsDto } from './fileCopyNaturalIdWsDto';
import { FileCopyStatusWsDto } from './fileCopyStatusWsDto';


export interface FileCopyWs { 
    id: string;
    naturalId: FileCopyNaturalIdWsDto;
    status: FileCopyStatusWsDto;
    failedReason?: string;
    filePath?: string;
    dateCreated?: string;
    dateModified?: string;
}
export namespace FileCopyWs {
}


