/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileCopyProcessingStatus = 'discovered' | 'enqueued' | 'processed';

export const FileCopyProcessingStatus = {
    Discovered: 'discovered' as FileCopyProcessingStatus,
    Enqueued: 'enqueued' as FileCopyProcessingStatus,
    Processed: 'processed' as FileCopyProcessingStatus
};

