/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SourceFileDetails } from './sourceFileDetails';
import { BackupDetails } from './backupDetails';


export interface FileDetails { 
    id: string;
    gameId: string;
    sourceFileDetails: SourceFileDetails;
    backupDetails: BackupDetails;
    dateCreated?: string;
    dateModified?: string;
}

