/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileCopyStatusWsDto = 'TRACKED' | 'ENQUEUED' | 'IN_PROGRESS' | 'STORED_INTEGRITY_UNKNOWN' | 'STORED_INTEGRITY_VERIFIED' | 'FAILED';

export const FileCopyStatusWsDto = {
    Tracked: 'TRACKED' as FileCopyStatusWsDto,
    Enqueued: 'ENQUEUED' as FileCopyStatusWsDto,
    InProgress: 'IN_PROGRESS' as FileCopyStatusWsDto,
    StoredIntegrityUnknown: 'STORED_INTEGRITY_UNKNOWN' as FileCopyStatusWsDto,
    StoredIntegrityVerified: 'STORED_INTEGRITY_VERIFIED' as FileCopyStatusWsDto,
    Failed: 'FAILED' as FileCopyStatusWsDto
};

