/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyNaturalId } from './fileCopyNaturalId';
import { FileCopyStatus } from './fileCopyStatus';


export interface FileCopy { 
    id: string;
    naturalId: FileCopyNaturalId;
    status: FileCopyStatus;
    failedReason?: string;
    filePath?: string;
    dateCreated?: string;
    dateModified?: string;
}
export namespace FileCopy {
}


