/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileBackupMessageTopics = '/topic/backups/started' | '/topic/backups/progress' | '/topic/backups/finished';

export const FileBackupMessageTopics = {
    Started: '/topic/backups/started' as FileBackupMessageTopics,
    Progress: '/topic/backups/progress' as FileBackupMessageTopics,
    Finished: '/topic/backups/finished' as FileBackupMessageTopics
};

