/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileBackupStartedEvent { 
    gameFileId: string;
    originalGameTitle: string;
    fileTitle: string;
    version: string;
    originalFileName: string;
    size: string;
    filePath?: string;
}

