/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileCopyStatus = 'DISCOVERED' | 'ENQUEUED' | 'IN_PROGRESS' | 'SUCCESS' | 'FAILED';

export const FileCopyStatus = {
    Discovered: 'DISCOVERED' as FileCopyStatus,
    Enqueued: 'ENQUEUED' as FileCopyStatus,
    InProgress: 'IN_PROGRESS' as FileCopyStatus,
    Success: 'SUCCESS' as FileCopyStatus,
    Failed: 'FAILED' as FileCopyStatus
};

