/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileDiscoveryWebSocketTopics = '/topic/file-discovery/file-discovered' | '/topic/file-discovery/file-status-changed' | '/topic/file-discovery/progress-update';

export const FileDiscoveryWebSocketTopics = {
    FileDiscovered: '/topic/file-discovery/file-discovered' as FileDiscoveryWebSocketTopics,
    FileStatusChanged: '/topic/file-discovery/file-status-changed' as FileDiscoveryWebSocketTopics,
    ProgressUpdate: '/topic/file-discovery/progress-update' as FileDiscoveryWebSocketTopics
};

