/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileBackupStatus = 'DISCOVERED' | 'ENQUEUED' | 'IN_PROGRESS' | 'SUCCESS' | 'FAILED';

export const FileBackupStatus = {
    Discovered: 'DISCOVERED' as FileBackupStatus,
    Enqueued: 'ENQUEUED' as FileBackupStatus,
    InProgress: 'IN_PROGRESS' as FileBackupStatus,
    Success: 'SUCCESS' as FileBackupStatus,
    Failed: 'FAILED' as FileBackupStatus
};

