/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileCopyStatusWsDto = 'DISCOVERED' | 'ENQUEUED' | 'IN_PROGRESS' | 'SUCCESS' | 'FAILED';

export const FileCopyStatusWsDto = {
    Discovered: 'DISCOVERED' as FileCopyStatusWsDto,
    Enqueued: 'ENQUEUED' as FileCopyStatusWsDto,
    InProgress: 'IN_PROGRESS' as FileCopyStatusWsDto,
    Success: 'SUCCESS' as FileCopyStatusWsDto,
    Failed: 'FAILED' as FileCopyStatusWsDto
};

