/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameFileInFileCopyContextWsDto } from './gameFileInFileCopyContextWsDto';
import { FileCopyWs } from './fileCopyWs';
import { GameInFileCopyContextWs } from './gameInFileCopyContextWs';


export interface FileCopyWithContextWs { 
    fileCopy: FileCopyWs;
    gameFile: GameFileInFileCopyContextWsDto;
    game: GameInFileCopyContextWs;
}

