/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileBackupStartedMessage { 
    gameFileDetailsId?: string;
    originalGameTitle?: string;
    fileTitle?: string;
    version?: string;
    originalFileName?: string;
    size?: string;
    filePath?: string;
}

