/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FileSourceWs { 
    gameProviderId: string;
    originalGameTitle: string;
    fileTitle: string;
    version: string;
    url: string;
    originalFileName: string;
    size: string;
}

