/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileBackupMessageTopics = '/topic/backups/progress-update' | '/topic/backups/status-changed';

export const FileBackupMessageTopics = {
    ProgressUpdate: '/topic/backups/progress-update' as FileBackupMessageTopics,
    StatusChanged: '/topic/backups/status-changed' as FileBackupMessageTopics
};

