/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyNaturalIdWsDto } from './fileCopyNaturalIdWsDto';


export interface FileDownloadProgressUpdatedEvent { 
    fileCopyId: string;
    fileCopyNaturalId: FileCopyNaturalIdWsDto;
    percentage: number;
    timeLeftSeconds: number;
}

