/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameFileInFileCopyContext } from './gameFileInFileCopyContext';
import { FileCopy } from './fileCopy';
import { GameInFileCopyContext } from './gameInFileCopyContext';


export interface FileCopyWithContext { 
    fileCopy: FileCopy;
    gameFile: GameFileInFileCopyContext;
    game: GameInFileCopyContext;
}

