/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileDiscoveryMessageTopics = '/topic/file-discovery';

export const FileDiscoveryMessageTopics = {
    TopicFileDiscovery: '/topic/file-discovery' as FileDiscoveryMessageTopics
};

