/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileDiscoveryWebSocketTopics = 'FILE_DISCOVERED' | 'FILE_DISCOVERY_STATUS_CHANGED' | 'FILE_DISCOVERY_PROGRESS_CHANGED';

export const FileDiscoveryWebSocketTopics = {
    Discovered: 'FILE_DISCOVERED' as FileDiscoveryWebSocketTopics,
    DiscoveryStatusChanged: 'FILE_DISCOVERY_STATUS_CHANGED' as FileDiscoveryWebSocketTopics,
    DiscoveryProgressChanged: 'FILE_DISCOVERY_PROGRESS_CHANGED' as FileDiscoveryWebSocketTopics
};

