/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileCopyStatus = 'TRACKED' | 'ENQUEUED' | 'IN_PROGRESS' | 'STORED_INTEGRITY_UNKNOWN' | 'STORED_INTEGRITY_VERIFIED' | 'FAILED';

export const FileCopyStatus = {
    Tracked: 'TRACKED' as FileCopyStatus,
    Enqueued: 'ENQUEUED' as FileCopyStatus,
    InProgress: 'IN_PROGRESS' as FileCopyStatus,
    StoredIntegrityUnknown: 'STORED_INTEGRITY_UNKNOWN' as FileCopyStatus,
    StoredIntegrityVerified: 'STORED_INTEGRITY_VERIFIED' as FileCopyStatus,
    Failed: 'FAILED' as FileCopyStatus
};

