/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FileDownloadMessageTopics = '/topic/downloads/started' | '/topic/downloads/progress' | '/topic/downloads/finished';

export const FileDownloadMessageTopics = {
    Started: '/topic/downloads/started' as FileDownloadMessageTopics,
    Progress: '/topic/downloads/progress' as FileDownloadMessageTopics,
    Finished: '/topic/downloads/finished' as FileDownloadMessageTopics
};

