/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyWithProgress } from './fileCopyWithProgress';
import { GameFile } from './gameFile';


export interface GameFileWithCopies { 
    gameFile: GameFile;
    fileCopiesWithProgress: Array<FileCopyWithProgress>;
}

