/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameContentDiscoveryWebSocketTopics = '/topic/game-content-discovery/file-discovered' | '/topic/game-content-discovery/status-changed' | '/topic/game-content-discovery/progress-update';

export const GameContentDiscoveryWebSocketTopics = {
    FileDiscovered: '/topic/game-content-discovery/file-discovered' as GameContentDiscoveryWebSocketTopics,
    StatusChanged: '/topic/game-content-discovery/status-changed' as GameContentDiscoveryWebSocketTopics,
    ProgressUpdate: '/topic/game-content-discovery/progress-update' as GameContentDiscoveryWebSocketTopics
};

