/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileDetailsResponse } from './fileDetailsResponse';


export interface GameDetailsResponse { 
    title?: string;
    backgroundImage?: string;
    cdKey?: string;
    textInformation?: string;
    files?: Array<FileDetailsResponse>;
    changelog?: string;
}

