/**
 * backend
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SourceFileWithCopies} from './sourceFileWithCopies';


export interface GameWithFileCopies {
    id: string;
    title: string;
    sourceFilesWithCopies: Array<SourceFileWithCopies>;
}

