/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameContentDiscoveryOutcomeWs } from './gameContentDiscoveryOutcomeWs';


export interface GameContentDiscoveryResultWs { 
    startedAt: string;
    stoppedAt: string;
    discoveryOutcome: GameContentDiscoveryOutcomeWs;
    lastSuccessfulDiscoveryCompletedAt?: string;
    gamesDiscovered: number;
    gameFilesDiscovered: number;
}
export namespace GameContentDiscoveryResultWs {
}


