/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileSource } from './fileSource';
import { FileCopy } from './fileCopy';


export interface GameFile { 
    id: string;
    gameId: string;
    fileSource: FileSource;
    fileCopy: FileCopy;
    dateCreated?: string;
    dateModified?: string;
}

