/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {FileStatus} from './fileStatus';


export interface GameFileVersion {
    id?: number;
    source?: string;
    url?: string;
    title?: string;
    originalFileName?: string;
    filePath?: string;
    gameTitle?: string;
    version?: string;
    size?: string;
    dateCreated?: string;
    dateModified?: string;
    status?: FileStatus;
    failedReason?: string;
}
export namespace GameFileVersion {
}


