/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameFileProcessingStatus = 'discovered' | 'enqueued' | 'processed';

export const GameFileProcessingStatus = {
    Discovered: 'discovered' as GameFileProcessingStatus,
    Enqueued: 'enqueued' as GameFileProcessingStatus,
    Processed: 'processed' as GameFileProcessingStatus
};

