/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameFileWithCopies } from './gameFileWithCopies';


export interface GameWithFileCopies { 
    id: string;
    title: string;
    gameFilesWithCopies: Array<GameFileWithCopies>;
}

