/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GameContentDiscoveryOutcome = {
    Success: 'SUCCESS',
    Failed: 'FAILED'
} as const;
export type GameContentDiscoveryOutcome = typeof GameContentDiscoveryOutcome[keyof typeof GameContentDiscoveryOutcome];

