/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Progress } from './progress';


export interface GameContentDiscoveryStatus { 
    gameProviderId: string;
    isInProgress: boolean;
    progress?: Progress;
}

