/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GameContentDiscoveryProgress { 
    percentage: number;
    timeLeftSeconds: number;
    gamesDiscovered: number;
    gameFilesDiscovered: number;
}

