/**
 * backend
 * The backend module built with Spring Boot
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SourceFileDetails} from './sourceFileDetails';
import {BackupDetails} from './backupDetails';


export interface GameFileDetails {
    id?: string;
    gameId?: string;
    sourceFileDetails?: SourceFileDetails;
    backupDetails?: BackupDetails;
    dateCreated?: string;
    dateModified?: string;
}

