/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameContentDiscoveryWebSocketTopics = '/topic/game-content-discovery/discovery-started' | '/topic/game-content-discovery/discovery-stopped' | '/topic/game-content-discovery/progress-update';

export const GameContentDiscoveryWebSocketTopics = {
    DiscoveryStarted: '/topic/game-content-discovery/discovery-started' as GameContentDiscoveryWebSocketTopics,
    DiscoveryStopped: '/topic/game-content-discovery/discovery-stopped' as GameContentDiscoveryWebSocketTopics,
    ProgressUpdate: '/topic/game-content-discovery/progress-update' as GameContentDiscoveryWebSocketTopics
};

