/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type GameContentDiscoveryOutcomeWs = 'SUCCESS' | 'FAILED';

export const GameContentDiscoveryOutcomeWs = {
    Success: 'SUCCESS' as GameContentDiscoveryOutcomeWs,
    Failed: 'FAILED' as GameContentDiscoveryOutcomeWs
};

