/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const GameContentDiscoveryWebSocketTopics = {
    TopicGameContentDiscoveryDiscoveryStarted: '/topic/game-content-discovery/discovery-started',
    TopicGameContentDiscoveryDiscoveryStopped: '/topic/game-content-discovery/discovery-stopped',
    TopicGameContentDiscoveryProgressUpdate: '/topic/game-content-discovery/progress-update'
} as const;
export type GameContentDiscoveryWebSocketTopics = typeof GameContentDiscoveryWebSocketTopics[keyof typeof GameContentDiscoveryWebSocketTopics];

