/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameContentDiscoveryOutcome } from './gameContentDiscoveryOutcome';


export interface GameContentDiscoveryResult { 
    startedAt: string;
    stoppedAt: string;
    discoveryOutcome: GameContentDiscoveryOutcome;
    lastSuccessfulDiscoveryCompletedAt?: string;
    gamesDiscovered: number;
    gameFilesDiscovered: number;
}
export namespace GameContentDiscoveryResult {
}


