/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopy } from './fileCopy';
import { GameFile } from './gameFile';


export interface GameFileWithCopies { 
    gameFile: GameFile;
    fileCopies: Array<FileCopy>;
}

