/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileSource } from './fileSource';


export interface GameFileInFileCopyContext { 
    fileSource: FileSource;
}

