/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameFile } from './gameFile';


export interface GameWithFiles { 
    id: string;
    title: string;
    files: Array<GameFile>;
}

