/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GogGameFile } from './gogGameFile';


export interface GogGameWithFiles { 
    title?: string;
    backgroundImage?: string;
    cdKey?: string;
    textInformation?: string;
    files?: Array<GogGameFile>;
    changelog?: string;
}

