/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type LogsMessageTopics = '/topic/logs';

export const LogsMessageTopics = {
    TopicLogs: '/topic/logs' as LogsMessageTopics
};

