/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const LogsMessageTopics = {
    TopicLogs: '/topic/logs'
} as const;
export type LogsMessageTopics = typeof LogsMessageTopics[keyof typeof LogsMessageTopics];

