/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameWithFileCopies } from './gameWithFileCopies';


export interface PageGameWithFileCopies { 
    content: Array<GameWithFileCopies>;
    size: number;
    totalPages: number;
    totalElements: number;
    pageSize: number;
    pageNumber: number;
}

