/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyWithContext } from './fileCopyWithContext';


export interface PageFileCopyWithContext { 
    content?: Array<FileCopyWithContext>;
    size?: number;
    totalPages?: number;
    totalElements?: number;
    pageSize?: number;
    pageNumber?: number;
}

