/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopyWithContext } from './fileCopyWithContext';
import { Pagination } from './pagination';


export interface PageFileCopyWithContext { 
    content: Array<FileCopyWithContext>;
    totalPages: number;
    totalElements: number;
    pagination: Pagination;
}

