/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Pagination } from './pagination';
import { GameWithFileCopies } from './gameWithFileCopies';


export interface PageGameWithFileCopies { 
    content: Array<GameWithFileCopies>;
    totalPages: number;
    totalElements: number;
    pagination: Pagination;
}

