/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FileCopy } from './fileCopy';


export interface PageFileCopy { 
    content?: Array<FileCopy>;
    size?: number;
    totalPages?: number;
    totalElements?: number;
    pageSize?: number;
    pageNumber?: number;
}

