/**
 * backend
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import {SourceFile} from './sourceFile';
import {FileCopyWithProgress} from './fileCopyWithProgress';


export interface SourceFileWithCopies {
    sourceFile: SourceFile;
    fileCopiesWithProgress: Array<FileCopyWithProgress>;
}

