/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StorageSolutionStatus = 'NOT_CONNECTED' | 'CONNECTED';

export const StorageSolutionStatus = {
    NotConnected: 'NOT_CONNECTED' as StorageSolutionStatus,
    Connected: 'CONNECTED' as StorageSolutionStatus
};

