/**
 * backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const StorageSolutionStatus = {
    NotConnected: 'NOT_CONNECTED',
    Connected: 'CONNECTED'
} as const;
export type StorageSolutionStatus = typeof StorageSolutionStatus[keyof typeof StorageSolutionStatus];

