/**
 * backend
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StorageSolutionStatus } from './storageSolutionStatus';


export interface StorageSolutionStatusesResponse {
    statuses: { [key: string]: StorageSolutionStatus; };
}

