package dev.codesoapbox.backity.buildtools;

import com.google.testing.compile.Compilation;
import com.google.testing.compile.CompilationSubject;
import com.google.testing.compile.JavaFileObjects;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.Arguments;
import org.junit.jupiter.params.provider.MethodSource;

import javax.annotation.processing.SupportedAnnotationTypes;
import javax.tools.JavaFileObject;
import java.io.IOException;
import java.util.stream.Stream;

import static com.google.testing.compile.Compiler.javac;
import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.jupiter.api.Named.named;
import static org.junit.jupiter.params.provider.Arguments.arguments;

class MultiAnnotationTestProcessorTest {

    private static final String TEST_DATA_PREFIX = "test/";

    static Stream<Arguments> validCompilationCases() {
        return Stream.of(
                arguments(named("properly annotated class ending with IT", "TestClassIT")),
                arguments(named("properly annotated class ending with Test", "TestClassTest")),
                arguments(named("properly annotated class with regex", "TestClassStrippingRegexIT")),
                arguments(named("meta-annotated class", "TestClassMetaAnnotatedIT")),
                arguments(named("processor annotation not present", "TestClassNotAnnotatedIT")),
                arguments(named("no concrete annotations", "TestClassNoConcreteAnnotationsIT")),
                arguments(named("child class already exists", "TestClassWithExistingChildIT"))
        );
    }

    static Stream<Arguments> generatedClassNameCases() {
        return Stream.of(
                arguments(
                        named("properly annotated class ending with IT", "TestClassIT"),
                        "TestClassConcreteAnnotationIT"
                ),
                arguments(
                        named("properly annotated class ending with Test", "TestClassTest"),
                        "TestClassConcreteAnnotationTest"
                ),
                arguments(
                        named("properly annotated class with regex", "TestClassStrippingRegexIT"),
                        "TestClassConcreteIT"
                ),
                arguments(
                        named("meta-annotated class", "TestClassMetaAnnotatedIT"),
                        "TestClassMetaAnnotatedConcreteAnnotationIT"
                )
        );
    }

    @ParameterizedTest(name = "compilation task should not fail given {0}")
    @MethodSource("validCompilationCases")
    void compilationTaskShouldNotFail(String parentClassSimpleName) {
        JavaFileObject parentClass = getTestClass(parentClassSimpleName);

        Compilation compilation = compile(parentClass);

        CompilationSubject.assertThat(compilation)
                .succeeded();
    }

    private JavaFileObject getTestClass(String classSimpleName) {
        return JavaFileObjects.forResource(TEST_DATA_PREFIX + classSimpleName + ".java");
    }

    private Compilation compile(JavaFileObject... parentClass) {
        return javac()
                .withProcessors(new MultiAnnotationTestProcessor())
                .compile(parentClass);
    }

    @ParameterizedTest(name = "should generate class with correct name given {0}")
    @MethodSource("generatedClassNameCases")
    void shouldGenerateClassWithCorrectName(String parentClassSimpleName, String generatedClassSimpleName) {
        JavaFileObject parentClass = getTestClass(parentClassSimpleName);

        Compilation compilation = compile(parentClass);

        CompilationSubject.assertThat(compilation)
                .generatedSourceFile(TEST_DATA_PREFIX + generatedClassSimpleName)
                .contentsAsUtf8String()
                .contains("public class " + generatedClassSimpleName + " extends " + parentClassSimpleName);
    }

    @Test
    void shouldGenerateCorrectContent() {
        JavaFileObject parentClass = getTestClass("TestClassIT");

        Compilation compilation = compile(parentClass);

        CompilationSubject.assertThat(compilation)
                .generatedSourceFile(TEST_DATA_PREFIX + "TestClassConcreteAnnotationIT")
                .contentsAsUtf8String()
                .isEqualTo("""
                        package test;
                        
                        import test.annotations.ConcreteAnnotation;
                        
                        /**
                         * Generated by dev.codesoapbox.backity.buildtools.MultiAnnotationTestProcessor.
                         */
                        @ConcreteAnnotation
                        public class TestClassConcreteAnnotationIT extends TestClassIT {
                        }
                        """);
    }

    @Test
    void shouldNotGenerateClassIfParentIsMetaAnnotation() {
        JavaFileObject parentClass = getTestClass("annotations/MetaAnnotatedMultiAnnotationTest");

        Compilation compilation = compile(parentClass);

        CompilationSubject.assertThat(compilation)
                .succeeded();
    }

    @Test
    void shouldNotGenerateClassIfChildClassAlreadyExists() {
        JavaFileObject parentClass = getTestClass("TestClassWithExistingChildIT");
        JavaFileObject originalChildClass =
                getTestClass("TestClassWithExistingChildConcreteAnnotationIT");

        Compilation compilation = compile(parentClass, originalChildClass);

        assertThat(compilation.generatedSourceFiles()).isEmpty();
    }

    @Test
    void shouldFailCompilationIfIOExceptionOccursDuringGeneration() {
        JavaFileObject parentClass = getTestClass("TestClassIT");

        Compilation compilation = javac()
                .withProcessors(new FailingMultiAnnotationTestProcessor())
                .compile(parentClass);

        CompilationSubject.assertThat(compilation)
                .failed();

        CompilationSubject.assertThat(compilation)
                .hadErrorContaining("Failed to generate TestClassIT: Simulated IO failure");
    }

    @SupportedAnnotationTypes("*")
    static class FailingMultiAnnotationTestProcessor extends MultiAnnotationTestProcessor {

        @Override
        protected JavaFileObject createSourceFile(String fullClassName,
                                                  GeneratedClassInfo generatedClassInfo)
                throws IOException {
            throw new IOException("Simulated IO failure");
        }
    }
}
