export * from './backupTargets.service';
import {BackupTargetsClient} from './backupTargets.service';
import {FileCopiesClient} from './fileCopies.service';
import {GOGClient} from './gOG.service';
import {GOGAuthenticationClient} from './gOGAuthentication.service';
import {GOGConfigurationClient} from './gOGConfiguration.service';
import {GameContentDiscoveryClient} from './gameContentDiscovery.service';
import {GamesClient} from './games.service';
import {H2DatabaseClient} from './h2Database.service';
import {StorageSolutionsClient} from './storageSolutions.service';

export * from './fileCopies.service';
export * from './gOG.service';
export * from './gOGAuthentication.service';
export * from './gOGConfiguration.service';
export * from './gameContentDiscovery.service';
export * from './games.service';
export * from './h2Database.service';
export * from './storageSolutions.service';
export const APIS = [BackupTargetsClient, FileCopiesClient, GOGClient, GOGAuthenticationClient, GOGConfigurationClient, GameContentDiscoveryClient, GamesClient, H2DatabaseClient, StorageSolutionsClient];
