export * from './fileDetails.service';
import { FileDetailsClient } from './fileDetails.service';
export * from './fileDiscovery.service';
import { FileDiscoveryClient } from './fileDiscovery.service';
export * from './gOG.service';
import { GOGClient } from './gOG.service';
export * from './gOGAuthentication.service';
import { GOGAuthenticationClient } from './gOGAuthentication.service';
export * from './games.service';
import { GamesClient } from './games.service';
export * from './h2Database.service';
import { H2DatabaseClient } from './h2Database.service';
export * from './logs.service';
import { LogsClient } from './logs.service';
export const APIS = [FileDetailsClient, FileDiscoveryClient, GOGClient, GOGAuthenticationClient, GamesClient, H2DatabaseClient, LogsClient];
