name: Deploy website

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # Minimal permissions required for building and uploading Pages artifact
    permissions:
      contents: read # required by actions/checkout
      pages: write # required by actions/configure-pages

    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Install, build, and upload your site
        # https://github.com/withastro/action
        uses: withastro/action@b7d53628f8b666036b0238aadb0b984a2a489f26 # v6
        with:
          path: ./website

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write # required to deploy to GitHub Pages
      id-token: write # required for OIDC authentication
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@cd2ce8fcbc39b97be8ca5fce6e763baed58fa128 # v5